-- Migration: Create Bibit and Bottles tables

-- 1. Create Bibit Table
CREATE TABLE IF NOT EXISTS public.bibit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    collection TEXT NOT NULL, -- 'Global Parfume' or 'Arabian Parfume'
    top_notes JSONB DEFAULT '[]'::jsonb, -- e.g. [{"note": "Citrus", "character": "Strong"}]
    middle_notes JSONB DEFAULT '[]'::jsonb,
    base_notes JSONB DEFAULT '[]'::jsonb,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Bottles Table
CREATE TABLE IF NOT EXISTS public.bottles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    capacity_ml INTEGER NOT NULL,
    price BIGINT NOT NULL,
    image_url TEXT,
    stock INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Trigger to update 'updated_at' on Bibit
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_bibit_modtime
BEFORE UPDATE ON public.bibit
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

CREATE TRIGGER update_bottles_modtime
BEFORE UPDATE ON public.bottles
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();
